### PR TITLE
kipolovnikov_extra-bonds

### PR DESCRIPTION
**Pull request by kipolovnikov**
Extra_bonds and extra_angles added as new parameters to the polymer_chains forcekit.
Several typos are corrected

### CODE REVIEW

**Comment by golobor** [comment]
quick question - why lumping extraBonds together with chains? The alternative is to just to add them via addForce(harmonicBonds(extra_bonds))

**Comment by mimakaev** [comment]
> 
> 
> quick question - why lumping extraBonds together with chains? The alternative is to just to add them via addForce(harmonicBonds(extra_bonds)). @kipolovnikov @mimakaev

That would create a second harmonic bond force. Is that how you do it?

**Comment by golobor** [comment]
yeah! Is there any downside to having a 2nd force?
Unless there is a slowdown, using a separate force would make the API a bit
cleaner (one tool for one task)

**Comment by mimakaev** [comment]
I will ask Peter if this is an OK thing to do... I'm less worried about the slowdown, and more worried about shared variables etc.

**Comment by golobor** [comment]
Ah! The names of variables are always modified such that the name of the
force is appended to them:
https://github.com/mirnylab/polychrom/blob/e38bdad9cdc2ee7ec49232007b83ed3934601f2c/polychrom/forces.py#L52

Or, that's not what you meant? In any case, in my simulations, I use a
separate force for, say, loops

**Comment by mimakaev** [comment]
Yes, the names are modified. I'm more worried about some internals of OpenMM. By construction, you are allowed to have several ExternalBondForce's, but maybe HarmonicBondForce has some internal state in OpenMM so having two of them may lead to some problems?

**Comment by mimakaev** [comment]
Peter says it's fine to have several forces of the same type. So should we go with that solution instead?

**Comment by kipolovnikov** [comment]
I don’t see why not to have an alternative solution. Extra_bonds and
extra_angles are empty lists by default. I remember, at some point I tried
to add another harmonic bond force and it raised some errors...



K

ср, 15 апр. 2020 г. в 21:41, Maksim Imakaev <notifications@github.com>:

**Comment by mimakaev** [comment]
OK, since it's only 4 lines, I think it's fine to have. 

Potential usecase: Caulobacter simulations (bottlebrush). It will be useful to have all the bonds and angles reported by the forcekit together, because both polymer bonds and "extra" bottlebrush bonds are true structural "polymer bonds", and not other type of bonds such as crosslinks/etc.

**Comment by mimakaev** [comment]
As it was difficult to merge, re-implemented it here. 
https://github.com/mirnylab/polychrom/pull/28

**Pull request closed without merging**
